### PR TITLE
Added digitalocean terraform sample

### PR DESCRIPTION
**Pull request by predominant**
Signed-off-by: Graham Weldon <graham@grahamweldon.com>

### CODE REVIEW

**Comment by danielcbright** [comment]
Hello @predominant , as someone who is very interested in seeing this PR be merged, I think it would be nice if you could follow the example set by the existing [AWS Terraform](https://github.com/habitat-sh/on-prem-builder/blob/master/terraform/aws/inputs.tf) code and be a bit more descriptive of your variables, as well as declaring type (with defaults where merited). Just my .02 (@chefsalim @eeyun)

**Comment by predominant** [comment]
Done @danielcbright

**Comment by chefsalim** [comment]
Looks good @predominant ... would you mind also squashing your commits?

**Comment by predominant** [comment]
@chefsalim Squashed

**Pull request merged**
